---

- name: restart docker
  sudo: yes
  service: name=docker state=restarted

- name: restart sshd
  sudo: yes
  service: name=ssh state=restarted

- name: reload iptables
  sudo: yes
  service: name=iptables-persistent state=restarted
