---

#- name: special case Suse systems
#  set_fact: server_user_group=users
#  when: (server_user_group is not defined) and (ansible_os_family == 'suse')

- name: add server admins and add them to admin groups
  user: >
    name={{ item }}
    shell="/bin/bash"
    groups=sudo,docker
    append=yes
  with_items: "{{ SERVER_ADMINS }}"

- name: add vagrant user to admin groups
  user: >
    name=vagrant
    groups=sudo,docker
    append=yes
  #when: ansible_user_id == "vagrant"

# TODO: hostkey needs to be fixed
#- name: add svn server to gobal known_hosts
#  known_hosts: >
#    path='/etc/ssh/ssh_known_hosts'
#    name='foo.com.invalid'
#    key="{{ lookup('file', 'pubkeys/foo.com.invalid') }}"
#    state=present

#  lineinfile: >
#    line="|1|T79zJdJg0e79Kcat5bFoJ4suBEI=|msDmUYG0KUZsJVaJ9jbboQsjkHA= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAoISLqXlxHRH7Wk1zFq4Y3oI/Aje40cUFhZ8Z7nYNrSj18lZjIyIeo/X8OR9CkTKQL/HILwFq9S+QSr1VjK6e8xTPyXzwYujwGscrjGHuCVNHnYo9u3PiaZbQ5Rew2JNgk6nt2ugsrT5QMUNWvAQHt+eBjfJ3wMl9aDfztQ9urrRtB1MKvdxsDC8/KFqn6WLfp/u4FVEDx3tGYCLCG1+Y0sY4/xsf2UbVtiX1NQe9WbKPemtWK9OFZ8i5wv8Zn23/1VO7TyoPl6tCf18pnXmApVVruIWHd0qJ2jlwlrQyZ3oRFjJfv0RnnaLnwrrvOMlH/jMz1Q8kRyowVh8mNiR+hQ=="
#    dest=/home/{{ item }}/.ssh/known_hosts
#    create=yes
#    mode=0600
#    owner={{ item }}
#    group={{ SERVER_user_group | default(item) }}

- name: add ssh key to authorized_keys
  authorized_key: >
    user="{{ item }}"
    key="{{ USER[item].ssh_key }}"
    state=present
  with_items: "{{ SERVER_ADMINS }}"

- name: no password for sudo needed
  lineinfile: >
    dest=/etc/sudoers
    state=present
    regexp='^%sudo ALL\='
    line='%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
    validate='visudo -cf %s'
