---

## SSHD Config

- name: disable dns resolving in sshd
  become: yes
  lineinfile: >
    line='UseDNS no'
    dest=/etc/ssh/sshd_config
    regexp="^#? *UseDNS"
    state=present
  notify:
    - restart sshd
