---
- name: elektropott
  docker:
    name: elektropott
    image: nginx
    pull: always
    restart_policy: always
    state: reloaded
    volumes:
      - "/srv/docker/elektropott/html:/usr/share/nginx/html:ro"

- name: wiki mysql
  docker:
    name: wiki-mysql
    image: mysql
    pull: always
    restart_policy: always
    state: reloaded
    volumes:
      - "/srv/docker/wiki-mysql:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "test"

- name: ldap
  docker:
    name: ldap
    image: labor/ldap
    pull: always
    restart_policy: always
    state: reloaded
    volumes:
      - "/srv/docker/ldap:/var/lib/ldap"
    env:
      SLAPD_PASSWORD: "test"

- name: wiki
  docker:
    name: wiki
    image: labor/wiki
    pull: always
    restart_policy: always
    state: reloaded
    volumes:
      - "/srv/docker/wiki:/var/www-shared/html"
    links:
      - "wiki-mysql:mysql"
      - "ldap:ldap"

- name: blog mysql
  docker:
    name: blog-mysql
    image: mysql
    pull: always
    restart_policy: always
    state: reloaded
    volumes:
      - "/srv/docker/blog-mysql:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "test2"

- name: blog
  docker:
    name: blog
    image: labor/blog
    pull: always
    restart_policy: always
    state: reloaded
    volumes:
      - "/srv/docker/blog:/var/www/html"
    links:
      - "blog-mysql:mysql"
      - "ldap:ldap"

- name: static websites
  docker:
    name: static-web
    image: labor/static-web
    pull: always
    restart_policy: always
    state: reloaded

- name: rev proxy
  docker:
    name: lfe
    image: labor/lfe
    pull: always
    restart_policy: always
    state: reloaded
    ports:
      - "80:80"
    links:
      - "blog:blog"
      - "wiki:wiki"
      - "elektropott:elektropott"
      - "static-web:static-web"

- name: xmpp
  docker:
    name: xmpp
    image: labor/xmpp
    pull: always
    restart_policy: always
    state: reloaded
    volumes:
      - "/srv/docker/xmpp:/var/lib/ejabberd"
    links:
      - "ldap:ldap"
